manifest:
  self:
    path: RobotOS_v1.0

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6.0
      import:
        name-allowlist:
            - cmsis
            - hal_stm32
            - hal_espressif
            - hal_nordic
            - segger